In [1]:
import pandas as pd

practice_data = [
    {
        "shipment_id": "S101",
        "warehouse": {
            "warehouse_id": "W01",
            "city": "Pune"
        },
        "tracking_events": ["Packed", "Shipped", "Delivered"]
    },
    {
        "shipment_id": "S102",
        "warehouse": {
            "warehouse_id": "W02",
            "city": "Mumbai"
        },
        "tracking_events": ["Packed", "Shipped"]
    },
    {
        "shipment_id": "S103",
        "warehouse": {
            "warehouse_id": "W01",
            "city": "Pune"
        },
        "tracking_events": []
    }
]

In [10]:
df = pd.json_normalize(practice_data, sep="_")

In [11]:
df

,shipment_id,tracking_events,warehouse_warehouse_id,warehouse_city
0,S101,"[Packed, Shipped, Delivered]",W01,Pune
1,S102,"[Packed, Shipped]",W02,Mumbai
2,S103,[],W01,Pune

In [12]:
df.explode('tracking_events')

  shipment_id tracking_events warehouse_warehouse_id warehouse_city
0        S101          Packed                    W01           Pune
0        S101         Shipped                    W01           Pune
0        S101       Delivered                    W01           Pune
1        S102          Packed                    W02         Mumbai
1        S102         Shipped                    W02         Mumbai
2        S103             NaN                    W01           Pune